# LibreLane configuration file

DESIGN_NAME: counter_32bit
VERILOG_FILES: dir::counter_32bit.sv
CLOCK_PORT: clk_i
CLOCK_PERIOD: 10 # 10ns = 100MHz

FP_SIZING: absolute
DIE_AREA: [0, 0, 175, 175]
PL_TARGET_DENSITY_PCT: 60

# We don't create cells at the top-level
SYNTH_ELABORATE_ONLY: true
FP_PDN_ENABLE_RAILS: false
RUN_CTS: false
PL_RESIZER_DESIGN_OPTIMIZATIONS: false
PL_RESIZER_TIMING_OPTIMIZATIONS: false
GLB_RESIZER_DESIGN_OPTIMIZATIONS: false
GLB_RESIZER_TIMING_OPTIMIZATIONS: false
PL_RESIZER_BUFFER_INPUT_PORTS: false
RUN_FILL_INSERTION: false
